### ISSUE TITLE
Make Command.replies a list of Reply instances 

### ISSUE THREAD

**Issue by wasndas** [sdss/clu#107]
Maybe you should give a warning before changing the client interface so drastically.

Why did you rename  _Command.replies[...].body_ to _Command.replies[...].message_ ?

Will the clu.client.AMQPClient.send_command() callback interface also be changed ? It still uses clu.client.AMQPReply as a parameter or will it also be using clu.base.Reply in the future ?

Most of the lvm is/was broken.

**Comment by albireox** [comment]
Sorry, that was not intended. I was trying to consolidate the interfaces and ended up renaming that attribute. I've release 1.5.8 that should have an alias from `Reply.body` to `Reply.message` so I think all the old functionality should be there. I don't plan to change `send_command()` right now; if I do I'll let you know.

**Comment by wasndas** [comment]
... from my side no problem, I have already changed it to  Reply.message, but other have probably some trouble.

For consistency it would be also good to have the same with the callback parameter from send_command, dont think anyone has used it, except me.
