### ISSUE TITLE
Provide standard way to handle error messages

### ISSUE THREAD

**Issue by albireox** [sdss/clu#90]
Often we catch an exception and then we need to format it. Instead, we should be able to pass the exception itself to `BaseActor.write()` and let it handle it. This would require the following:

- For `AMQPActor`, output `error` as a dictionary with `message` and maybe a few other parts of the exception. In the schema, allow `error` to be a dictionary or a string.
- For `LegacyActor`, `error` must be a string with the exception message.
- Change the default keyword for `.fail()` and `.error()` to use `error`.

**Comment by wasndas** [comment]
To pass an exception from the actor side:

     try:
         ---snip---
     except Exception as ex:
         return command.fail(error=ex.__repr__())

and on the client side im am using:

    def _stringToException(errstr):
        """converts a string to an exception object"""
        try:
           return eval(errstr)
   
        except SyntaxError as e:
           return ProxyPlainMessagException(errstr)
   
        except Exception as e:
           return Exception("Unexpected exception in parsing exception string", e)
     
At least that is working for me with my rpc style clu [proxy](https://github.com/wasndas/skymakercam/blob/master/utils/proxy_pwi_test.py) and here is an [example](https://github.com/wasndas/skymakercam/blob/master/utils/proxy_pwi_test.py)

**Comment by albireox** [comment]
Yes, this is the same idea, but with the ability of just passing `return command.fail(error=ex)` and CLU handing the output of the exception object in a nice and standardised way.
